---
- name: Run frontend Docker container
  community.docker.docker_container:
    name: frontend
    image: "{{ frontend_image | default('mohamedanwar121/frontend:latest') }}"
    pull: true
    state: started
    restart_policy: always
    ports:
      - "80:80"
    env:
      # Inject the API URL environment variable for Vite if we are grabbing it from inventory or playbooks
      VITE_API_URL: "{{ backend_url | default('http://backend:8000') }}"
  become: true
