---
- name: Configure frontend servers
  hosts: tag_Role_frontend
  become: true

  vars:
    backend_url: "internal-myapp-prod-internal-alb-2055366401.us-east-1.elb.amazonaws.com:80"
    project: myapp
    app_env: prod

  roles:
    - common
    - frontend
